[package]
name = "pea-pay"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0"
description = "Peacash Pay"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-address = { version = "0.6", path = "../address" }
pea-int = { version = "0.4", path = "../int" }
pea-core = { version = "0.6", path = "../core" }
pea-api-core = { version = "0.1", path = "../api-core" }
pea-pay-core = { version = "0.1", path = "../pay-core" }
pea-pay-db = { version = "0.1", path = "../pay-db" }
pea-key = { version = "0.6", path = "../key" }
pea-logger = { version = "0.1", path = "../logger" }
pea-transaction = { version = "0.8", path = "../transaction" }
pea-wallet = { version = "0.6", path = "../wallet" }
pea-util = { version = "0.1", path = "../util" }
hex = "0.4"
clap = { version = "3.2", features = ["derive"] }
lazy_static = "1.4"
regex = "1.6"
log = "0.4"
colored = "2.0"
futures = "0.3"
serde_json = "1.0"
bincode = "1.3"
reqwest = { version = "0.11", features = ["json"] }
rocksdb = "0.19"
tempdir = "0.3"
chrono = "0.4"
tokio = { version = "1.23", features = ["full"] }
axum = "0.6"
tower-http = { version = "0.3", features = ["cors"] }