[package]
name = "tofuri-pay"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri Pay"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1", path = "../address" }
tofuri-int = { version = "0.1", path = "../int" }
tofuri-core = { version = "0.1", path = "../core" }
tofuri-api-core = { version = "0.1", path = "../api-core" }
tofuri-pay-core = { version = "0.1", path = "../pay-core" }
tofuri-pay-db = { version = "0.1", path = "../pay-db" }
tofuri-key = { version = "0.1", path = "../key" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
tofuri-util = { version = "0.1", path = "../util" }
hex = "0.4"
clap = { version = "4.2", features = ["derive", "env"] }
lazy_static = "1.4"
regex = "1.6"
tracing = "0.1"
serde_json = "1.0"
bincode = "1.3"
reqwest = { version = "0.11", features = ["json"] }
rocksdb = "0.20"
tempdir = "0.3"
chrono = "0.4"
tokio = { version = "1.23", features = ["full"] }
axum = "0.6"
tower-http = { version = "0.3", features = ["cors"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
