[package]
name = "tofuri"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1", path = "../address" }
tofuri-api-internal-core = { version = "0.1", path = "../api-internal-core" }
tofuri-int = { version = "0.1", path = "../int" }
tofuri-block = { version = "0.1", path = "../block" }
tofuri-blockchain = { version = "0.1", path = "../blockchain" }
tofuri-blockchain-sync = { version = "0.1", path = "../blockchain-sync" }
tofuri-core = { version = "0.1", path = "../core" }
tofuri-db = { version = "0.1", path = "../db" }
tofuri-p2p = { version = "0.1", path = "../p2p" }
tofuri-key = { version = "0.1", path = "../key" }
tofuri-stake = { version = "0.1", path = "../stake" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
tofuri-tree = { version = "0.1", path = "../tree" }
tofuri-util = { version = "0.1", path = "../util" }
tofuri-wallet = { version = "0.1", path = "../wallet" }
rocksdb = "0.19"
colored = "2.0"
bincode = "1.3"
tracing = "0.1"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempdir = "0.3"
clap = { version = "3.2", features = ["derive"] }
void = "1.0"
tokio = { version = "1.24", features = ["full"] }
libp2p = { version = "0.50", features = ["noise","mplex","tcp"] }
sha2 = "0.10"
rand = "0.8"
chrono = "0.4"
tracing-subscriber = "0.3"