[package]
name = "tofuri"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/tofuri/tofuri"
default-run = "tofuri"

[dependencies]
tofuri-address = { version = "0.1", path = "../address" }
tofuri-rpc-core = { version = "0.1", path = "../rpc-core" }
tofuri-int = { version = "0.1", path = "../int" }
tofuri-block = { version = "0.1", path = "../block" }
tofuri-blockchain = { version = "0.1", path = "../blockchain" }
tofuri-sync = { version = "0.1", path = "../sync" }
tofuri-core = { version = "0.1", path = "../core" }
tofuri-db = { version = "0.1", path = "../db" }
tofuri-p2p = { version = "0.1", path = "../p2p" }
tofuri-key = { version = "0.1", path = "../key" }
tofuri-stake = { version = "0.1", path = "../stake" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
tofuri-tree = { version = "0.1", path = "../tree" }
tofuri-util = { version = "0.1", path = "../util" }
rocksdb = "0.21"
colored = "2"
bincode = "1"
tracing = "0.1"
hex = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempdir = "0.3"
clap = { version = "4", features = ["derive", "env"] }
void = "1"
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.51", features = ["noise", "mplex", "tcp"] }
sha2 = "0.10"
rand = "0.8"
chrono = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
