[package]
name = "tofuri"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri"
readme = "crate.md"
categories = ["cryptography::cryptocurrencies"]
repository = "https://github.com/tofuri/tofuri"
default-run = "tofuri"

[dependencies]
tofuri-address = { version = "0.1.1", path = "../address" }
tofuri-rpc = { version = "0.1.0", path = "../rpc" }
vint = { git = "https://github.com/zudo/vint" }
decimal = { git = "https://github.com/zudo/decimal" }
tofuri-block = { version = "0.1.0", path = "../block" }
tofuri-blockchain = { version = "0.1.0", path = "../blockchain" }
tofuri-db = { version = "0.1.0", path = "../db" }
tofuri-p2p = { version = "0.1.0", path = "../p2p" }
tofuri-key = { version = "0.1.0", path = "../key" }
tofuri-stake = { version = "0.1.0", path = "../stake" }
tofuri-transaction = { version = "0.1.0", path = "../transaction" }
rocksdb = "0.21.0"
colored = "2.0.0"
bincode = "1.3.3"
tracing = "0.1.37"
hex = "0.4.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tempdir = "0.3.7"
clap = { version = "4.2.7", features = ["derive", "env"] }
void = "1.0.2"
tokio = { version = "1.28.1", features = ["full"] }
libp2p = { version = "0.51.3", features = ["noise", "mplex", "tcp"] }
sha2 = "0.10.6"
rand = "0.8.5"
chrono = "0.4.24"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
