[package]
name = "tofuri"
version = "0.1.0"
edition = "2021"
default-run = "tofuri"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address = { path = "../address" }
api = { path = "../api" }
vint = { git = "https://github.com/zudo/vint" }
decimal = { git = "https://github.com/zudo/decimal" }
block = { path = "../block" }
blockchain = { path = "../blockchain" }
db = { path = "../db" }
key = { path = "../key" }
stake = { path = "../stake" }
transaction = { path = "../transaction" }
rocksdb = "0.21.0"
colored = "2.0.0"
bincode = "1.3.3"
tracing = "0.1.37"
hex = "0.4.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tempdir = "0.3.7"
clap = { version = "4.2.7", features = ["derive", "env"] }
void = "1.0.2"
tokio = { version = "1.28.1", features = ["full"] }
sha2 = "0.10.6"
rand = "0.8.5"
chrono = "0.4.24"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
axum = "0.6.18"
tower-http = { version = "0.4.0", features = ["cors", "trace"] }
libp2p = { version = "0.51.3", features = [
    "yamux",
    "noise",
    "tcp",
    "request-response",
    "autonat",
    "macros",
    "identify",
    "mdns",
    "gossipsub",
    "tokio",
] }
async-trait = "0.1.68"
futures = "0.3.28"
