[workspace]
members = [
    "address",
    "api",
    "api-core",
    "api-internal",
    "api-internal-core",
    "api-util",
    "block",
    "blockchain",
    "blockchain-sync",
    "core",
    "db",
    "fork",
    "int",
    "key",
    "p2p",
    "pay",
    "pay-core",
    "pay-db",
    "tofuri",
    "stake",
    "transaction",
    "tree",
    "util",
    "wallet"
]