[workspace]
members = [
    "address",
    "api",
    "rpc",
    "block",
    "blockchain",
    "db",
    "decimal",
    "key",
    "p2p",
    "pay",
    "tofuri",
    "stake",
    "transaction",
    "vint",
    "wallet",
]
