[workspace]
members = [
    "address",
    "api",
    "api-core",
    "block",
    "blockchain",
    "core",
    "db",
    "int",
    "key",
    "logger",
    "p2p",
    "pea",
    "stake",
    "transaction",
    "tree",
    "util",
    "wallet"
]