[workspace]
members = [
    "address",
    "api",
    "api-core",
    "rpc",
    "rpc-core",
    "api-util",
    "block",
    "blockchain",
    "sync",
    "db",
    "fork",
    "key",
    "p2p",
    "parseint",
    "pay",
    "pay-core",
    "pay-db",
    "tofuri",
    "stake",
    "transaction",
    "tree",
    "util",
    "varint",
    "wallet",
]
