FROM rust:latest as builder
WORKDIR /a
COPY . .
RUN cargo build --bin tofuri-wallet --release
FROM debian:stable-slim
COPY --from=builder /a/target/release/tofuri-wallet /usr/local/bin/
EXPOSE 2022
ENTRYPOINT ["tofuri-wallet"]