version: "3.1"
services:
  tofuri-pay:
    build:
      context: .
      dockerfile: dockerfile.pay
    restart: unless-stopped
    ports:
      - "2023:2023"
    command: [
      "--api=http://tofuri-api:2022",
      "--wallet=${WALLET}",
      "--passphrase=${PASSPHRASE}"
    ]
    volumes:
      - ./tofuri-wallet:/tofuri-wallet
      - ./tofuri-pay-db:/tofuri-pay-db