FROM rust:latest as build
WORKDIR /usr/src/tofuri
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    cmake \
    clang \
    protobuf-compiler \
    libssl-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cargo build --bin tofuri-wallet --release
FROM debian:stable-slim
COPY --from=build /usr/src/tofuri/target/release/tofuri-wallet /usr/local/bin/
EXPOSE 2022
ENTRYPOINT ["tofuri-wallet"]