version: "3.1"
services:
  tofuri-pay:
    build:
      context: .
      dockerfile: dockerfile.pay
    restart: unless-stopped
    ports:
      - "2023:2023"
    volumes:
      - ./tofuri-pay-db:/tofuri-pay-db
    env_file:
      - .env
    environment:
      - API=http://tofuri-api:2022
      - SECRET=${SECRET}
