FROM rust:latest as build
WORKDIR /usr/src/tofuri
COPY . .
RUN cargo build --bin tofuri-api --release
FROM debian:stable-slim
COPY --from=build /usr/src/tofuri/target/release/tofuri-api /usr/local/bin/
EXPOSE 2022
ENTRYPOINT ["tofuri-api"]