[package]
name = "tofuri-block"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri block"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-core = { version = "0.1", path = "../core" }
tofuri-key = { version = "0.1", path = "../key", features = ["vrf"] }
tofuri-stake = { version = "0.1", path = "../stake" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
tofuri-address = { version = "0.1", path = "../address" }
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
sha2 = "0.10"
merkle-cbt = "0.3"
hex = "0.4"
