[package]
name = "pea-int"
version = "0.4.2"
edition = "2021"
license = "GPL-3.0"
description = "Peacash integer"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { version = "0.6", path = "../core" }