[package]
name = "pea-address"
version = "0.6.3"
edition = "2021"
license = "GPL-3.0"
description = "Peacash address"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { version = "0.6", path = "../core" }
hex = "0.4"
sha2 = "0.10"