[package]
name = "tofuri-address"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri address"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-core = { version = "0.1", path = "../core" }
hex = "0.4"
sha2 = "0.10"