[package]
name = "pea-p2p"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-core = { version = "0.6", path = "../core" }
pea-util = { version = "0.1", path = "../util" }
libp2p = { version = "0.50", features = ["request-response","autonat","macros","identify","mdns","gossipsub","tokio"] }
tokio = "1.24"
async-trait = "0.1"
futures = "0.3"