[package]
name = "tofuri-util"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri utilities"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-block = { version = "0.1", path = "../block" }
tofuri-core = { version = "0.1", path = "../core" }
tofuri-stake = { version = "0.1", path = "../stake" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
bincode = "1.3"
lazy_static = "1.4"
chrono = "0.4"
sha2 = "0.10"
uint = "0.9"
tokio = { version = "1.24", features = ["full"] }
tracing = "0.1"
colored = "2.0"