[package]
name = "pea-util"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "エンドウ"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-block = { version = "0.6", path = "../block" }
pea-core = { version = "0.6", path = "../core" }
pea-stake = { version = "0.7", path = "../stake" }
pea-transaction = { version = "0.8", path = "../transaction" }
bincode = "1.3"
lazy_static = "1.4"
chrono = "0.4"
sha2 = "0.10"
uint = "0.9"