[package]
name = "tofuri-util"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri utilities"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-block = { version = "0.1.0", path = "../block" }
tofuri-core = { version = "0.1.0", path = "../core" }
tofuri-stake = { version = "0.1.0", path = "../stake" }
tofuri-transaction = { version = "0.1.0", path = "../transaction" }
bincode = "1.3.3"
lazy_static = "1.4.0"
chrono = "0.4.24"
sha2 = "0.10.6"
uint = "0.9.5"
tokio = { version = "1.28.1", features = ["full"] }
tracing = "0.1.37"
colored = "2.0.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
multiaddr = "0.17.0"
