[package]
name = "pea-blockchain"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"
description = "Peacash blockchain"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-address = { version = "0.6", path = "../address" }
pea-int = { version = "0.4", path = "../int" }
pea-block = { version = "0.6", path = "../block" }
pea-core = { version = "0.6", path = "../core" }
pea-db = { version = "0.7", path = "../db" }
pea-logger = { version = "0.1", path = "../logger" }
pea-key = { version = "0.6", path = "../key" }
pea-stake = { version = "0.7", path = "../stake" }
pea-transaction = { version = "0.8", path = "../transaction" }
pea-tree = { version = "0.4", path = "../tree" }
pea-util = { version = "0.1", path = "../util" }
rocksdb = "0.19"
colored = "2.0"
log = "0.4"
hex = "0.4"
lazy_static = "1.4"