[package]
name = "tofuri-blockchain"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri blockchain"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1.1", path = "../address" }
vint = { path = "../vint" }
decimal = { path = "../decimal" }
tofuri-block = { version = "0.1.0", path = "../block" }
tofuri-db = { version = "0.1.0", path = "../db" }
tofuri-fork = { version = "0.1.0", path = "../fork" }
tofuri-key = { version = "0.1.0", path = "../key" }
tofuri-stake = { version = "0.1.0", path = "../stake" }
tofuri-transaction = { version = "0.1.0", path = "../transaction" }
rocksdb = "0.21.0"
colored = "2.0.0"
tracing = "0.1.37"
hex = "0.4.3"
serde = "1.0.163"
lazy_static = "1.4.0"
bincode = "1.3.3"
chrono = "0.4.26"
