[package]
name = "tofuri-blockchain"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri blockchain"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1", path = "../address" }
tofuri-int = { version = "0.1", path = "../int" }
tofuri-block = { version = "0.1", path = "../block" }
tofuri-core = { version = "0.1", path = "../core" }
tofuri-db = { version = "0.1", path = "../db" }
tofuri-key = { version = "0.1", path = "../key" }
tofuri-stake = { version = "0.1", path = "../stake" }
tofuri-transaction = { version = "0.1", path = "../transaction" }
tofuri-tree = { version = "0.1", path = "../tree" }
tofuri-util = { version = "0.1", path = "../util" }
rocksdb = "0.19"
colored = "2.0"
tracing = "0.1"
hex = "0.4"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }