[package]
name = "vanity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
address = { git = "https://github.com/tofuri/tofuri" }
key = { git = "https://github.com/tofuri/tofuri" }
clap = { version = "4.3.2", features = ["derive"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1.37"
