[package]
name = "tofuri-rpc-core"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri RPC core"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
serde = { version = "1.0", features = ["derive"] }