[package]
name = "tofuri-tree"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri tree"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-core = { version = "0.1", path = "../core" }