[package]
name = "tofuri-api"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri API"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1.1", path = "../address" }
tofuri-block = { version = "0.1.0", path = "../block" }
tofuri-blockchain = { version = "0.1.0", path = "../blockchain" }
tofuri-key = { version = "0.1.0", path = "../key" }
vint = { git = "https://github.com/zudo/vint" }
decimal = { git = "https://github.com/zudo/decimal" }
tofuri-stake = { version = "0.1.0", path = "../stake" }
tofuri-transaction = { version = "0.1.0", path = "../transaction" }
serde = { version = "1.0.163", features = ["derive"] }
hex = "0.4.3"
