[package]
name = "tofuri-api"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "Tofuri API"
repository = "https://github.com/tofuri/tofuri"

[dependencies]
tofuri-address = { version = "0.1.1", path = "../address" }
tofuri-core = { version = "0.1.0", path = "../core" }
tofuri-rpc = { version = "0.1.0", path = "../rpc" }
tofuri-api-core = { version = "0.1.0", path = "../api-core" }
tofuri-api-util = { version = "0.1.0", path = "../api-util" }
tofuri-block = { version = "0.1.0", path = "../block" }
tofuri-int = { version = "0.1.0", path = "../int" }
tofuri-stake = { version = "0.1.0", path = "../stake" }
tofuri-transaction = { version = "0.1.0", path = "../transaction" }
tofuri-util = { version = "0.1.0", path = "../util" }
serde = { version = "1.0.163", features = ["derive"] }
tokio = { version = "1.28.1", features = ["full"] }
hex = "0.4.3"
axum = "0.6.18"
tower-http = { version = "0.4.0", features = ["cors", "trace"] }
clap = { version = "4.2.7", features = ["derive", "env"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1.37"
