[package]
name = "pea-api"
version = "0.6.3"
edition = "2021"
license = "GPL-3.0"
description = "Peacash API"
repository = "https://github.com/peacash/peacash"

[dependencies]
pea-stake = { version = "0.7", path = "../stake" }
pea-transaction = { version = "0.8", path = "../transaction" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24", features = ["full"] }
serde_json = "1.0"